name: flutter_state_management_example
description: Example
version: 0.0.1
homepage: https://github.com/MohiuddinM/ezbloc_flutter

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_state_management: ^0.6.0
#  flutter_state_management:
#    path: ../../flutter_state_management
  path_provider: ^2.1.4
  path: ^1.9.0
  isar_key_value: ^0.3.0

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^2.0.3