name: flutter_state_management
description: A collection of helper classes to make the use of ChangeNotifier easier for state management
version: 0.0.2
homepage: https://github.com/MohiuddinM/flutter_state_management

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  isar_key_value: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: